### ISSUE TITLE
[regression] Fails to build on FreeBSD

### ISSUE THREAD

**Issue by jbeich** [nuspell/nuspell#39]
| key                                       |    value     |
|-------------------------------------------|--------------|
| Operating system, distribution, version = | FreeBSD 11.3 |
| Nuspell version                         = | cacd0c8040d5 |

## Steps to reproduce

```
$ pkg install git cmake ninja icu boost-libs
$ git clone https://github.com/nuspell/nuspell/
$ cd nuspell
$ git submodule update --init --recursive
$ cmake -GNinja .
$ ninja
```

## Bugged behavior (output)

Regressed by 63a696f8c354
```c++
[5/29] Building CXX object src/nuspell/CMakeFiles/nuspell.dir/locale_utils.cxx.o
FAILED: src/nuspell/CMakeFiles/nuspell.dir/locale_utils.cxx.o
/usr/bin/c++   -isystem /usr/local/include -std=gnu++14 -MD -MT src/nuspell/CMakeFiles/nuspell.dir/locale_utils.cxx.o -MF src/nuspell/CMakeFiles/nuspell.dir/locale_utils.cxx.o.d -o src/nuspell/CMakeFiles/nuspell.dir/locale_utils.cxx.o -c src/nuspell/locale_utils.cxx
src/nuspell/locale_utils.cxx:37:2: error: "Platform has poor Unicode support. wchar_t must be Unicode."
#error "Platform has poor Unicode support. wchar_t must be Unicode."
 ^
1 error generated.
ninja: build stopped: subcommand failed.
```

## Expected behavior (output)

```
[29/29] Linking CXX executable tests/unit_test
```

# Change/feature request

Restore `&& !defined(__FreeBSD__)` and [maybe](https://github.com/DragonFlyBSD/DeltaPorts/commit/40525612077f) add `&& !defined(__DragonFly__)`. None of [ICU conditionals](https://github.com/unicode-org/icu/blob/release-64-2/icu4c/source/common/unicode/umachine.h#L255-L275) match even on development version of FreeBSD.
